#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from generate_capability_holdout import case, expected, inp


OUT = Path("data/capability_planning/taskframe_holdout_50.jsonl")


CASES = [
    case("taskframe_missing_press_release_001", "missing_input", "Make my press release intro punchier.", expected(final=["press release", "punchier"], inputs=[inp("press release", False, "unknown")], missing=["press release"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_podcast_transcript_001", "missing_input", "Summarize the podcast transcript into five takeaways.", expected(final=["summarize", "podcast"], inputs=[inp("transcript", False, "unknown")], missing=["transcript"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_budget_chart_001", "missing_input", "Chart budget by department for June.", expected(final=["chart", "budget"], inputs=[inp("budget", False, "unknown")], missing=["budget"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_uploaded_diagram_001", "missing_input", "What does the uploaded architecture diagram show?", expected(final=["diagram"], inputs=[inp("diagram", False, "unknown")], missing=["diagram"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_agreement_001", "missing_input", "Extract renewal obligations from the vendor agreement I attached.", expected(final=["extract", "obligations"], inputs=[inp("agreement", False, "unknown")], missing=["agreement"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_oneliner_001", "missing_input", "Polish the product one-liner so it sounds less generic.", expected(final=["polish", "one-liner"], inputs=[inp("one-liner", False, "unknown")], missing=["one-liner"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_interview_notes_001", "missing_input", "Turn my customer interview notes into themes.", expected(final=["themes", "interview"], inputs=[inp("notes", False, "unknown")], missing=["notes"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),
    case("taskframe_missing_survey_export_001", "missing_input", "Analyze the survey export for top complaints.", expected(final=["analyze", "survey"], inputs=[inp("survey", False, "unknown")], missing=["survey"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"])),

    case("taskframe_pasted_blockers_001", "pasted_text_analysis", "Pull blockers from these standup notes:\n\nAlice is waiting on legal. Ben needs test credentials. Cam has no blockers.", expected(final=["blockers", "standup"], inputs=[inp("standup notes", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["analyze_provided_text"])),
    case("taskframe_pasted_classify_comments_001", "pasted_text_analysis", "Categorize these comments as praise, bug, or question:\n1. Love the new dashboard.\n2. Export fails on Safari.\n3. Where is billing history?", expected(final=["categorize", "comments"], inputs=[inp("comments", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["classify_provided_text"])),
    case("taskframe_pasted_roster_table_001", "pasted_text_transform", "Turn this roster into a Markdown table: Ava - Eng - remote; Mo - Sales - NYC; Li - Ops - hybrid.", expected(final=["Markdown table"], inputs=[inp("roster", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["transform_text_format"])),
    case("taskframe_pasted_translate_german_001", "pasted_text_transform", "Translate this announcement into German: The migration window starts at 8 PM UTC.", expected(final=["translate", "German"], inputs=[inp("announcement", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["translate_text"])),
    case("taskframe_pasted_compare_ctas_001", "pasted_text_analysis", "Compare these CTAs and pick the more direct one.\n\nA: Start simplifying approvals today.\n\nB: See how teams save time with approval automation.", expected(final=["compare", "CTAs"], inputs=[inp("CTAs", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["compare_texts"])),
    case("taskframe_pasted_exception_001", "pasted_text_analysis", "Explain this exception:\n\nValueError: invalid literal for int() with base 10: 'N/A' in import_rows.py:88", expected(final=["explain", "exception"], inputs=[inp("exception", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["analyze_provided_text"])),
    case("taskframe_pasted_policy_rewrite_001", "pasted_text_transform", "Rewrite this policy blurb to be clearer: Users may initiate cancellation after the current renewal term has elapsed.", expected(final=["rewrite", "policy"], inputs=[inp("policy blurb", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["revise_text_for_clarity"])),
    case("taskframe_pasted_memo_summary_001", "pasted_text_analysis", "Summarize this memo in two bullets: The launch moves to August. Security review is complete. Sales enablement needs one more demo.", expected(final=["summarize", "memo"], inputs=[inp("memo", True, "pasted_text")], current=False, include_actions=["none"], include_caps=["summarize_document"])),

    case("taskframe_csv_average_001", "structured_data", "From this CSV, compute average response time by team:\nteam,response_time\nA,4\nA,6\nB,3", expected(final=["average", "response"], inputs=[inp("CSV", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["calculation"], include_caps=["analyze_provided_dataset"])),
    case("taskframe_tsv_count_001", "structured_data", "From this TSV, count tickets by severity:\nseverity\ttickets\nHigh\t4\nLow\t9\nHigh\t3", expected(final=["count", "tickets"], inputs=[inp("TSV", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["calculation"], include_caps=["analyze_provided_dataset"])),
    case("taskframe_semicolon_spend_001", "structured_data", "Aggregate spend by vendor from this table:\nvendor;spend\nApex;50\nNova;70\nApex;25", expected(final=["aggregate", "spend"], inputs=[inp("table", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["calculation"], include_caps=["analyze_provided_dataset"])),
    case("taskframe_pipe_chart_001", "structured_data", "Graph signups by source from this data:\nsource|signups\nAds|120\nOrganic|95", expected(final=["graph", "signups"], inputs=[inp("data", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["calculation"], include_caps=["generate_chart"])),
    case("taskframe_json_filter_001", "structured_data", "From this JSON, list overdue tasks: [{\"task\":\"invoice\",\"overdue\":true},{\"task\":\"demo\",\"overdue\":false}]", expected(final=["overdue", "tasks"], inputs=[inp("JSON", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["none"], include_caps=["analyze_provided_dataset"])),
    case("taskframe_table_sort_001", "structured_data", "From this table, list projects sorted by due date:\nproject,due_date\nApollo,2026-07-09\nBeacon,2026-07-05", expected(final=["sorted", "due date"], inputs=[inp("table", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["none"], include_caps=["analyze_provided_dataset"])),
    case("taskframe_attached_csv_refunds_001", "structured_data", "Compute refunds by channel from the attached CSV.", expected(final=["refunds", "channel"], inputs=[inp("CSV", True, "structured_data")], include_formats=["structured_data"], current=False, include_actions=["file_reading", "calculation"], include_caps=["analyze_provided_dataset"]), attachments=[{"name": "refunds_by_channel.csv", "format": "structured_data", "available": True}]),

    case("taskframe_url_summary_001", "url_summary", "Summarize the main claim in https://example.com/research-note.", expected(final=["summarize"], inputs=[inp("https://example.com/research-note", True, "url")], current=True, include_actions=["web_search"], include_caps=["retrieve_external_information"], alt_caps=["summarize_document"])),
    case("taskframe_url_compare_001", "url_summary", "Compare onboarding docs at https://example.com/v1 and https://example.com/v2.", expected(final=["compare", "onboarding"], inputs=[inp("https://example.com/v1", True, "url")], current=True, include_actions=["web_search"], include_caps=["compare_texts"], precede=[{"before": "retrieve", "after": "compare"}])),
    case("taskframe_current_kubernetes_001", "current_fact", "What is the latest Kubernetes minor release?", expected(final=["latest", "Kubernetes"], inputs=[inp("Kubernetes", True, "none")], current=True, include_actions=["web_search"], include_caps=["retrieve_current_information"])),
    case("taskframe_current_stock_001", "current_fact", "What is Nvidia's stock price right now?", expected(final=["stock", "Nvidia"], inputs=[inp("stock", True, "none")], current=True, include_actions=["web_search"], include_caps=["retrieve_current_information"])),
    case("taskframe_fact_check_mayor_001", "fact_check", "Fact-check whether Seattle's mayor announced a housing plan this week.", expected(final=["fact", "mayor"], inputs=[inp("mayor", True, "none")], current=True, include_actions=["web_search", "fact_checking"], include_caps=["verify_current_information"], precede=[{"before": "verify", "after": "answer"}])),
    case("taskframe_weather_tomorrow_001", "current_fact", "Will it rain in Austin tomorrow?", expected(final=["rain", "Austin"], inputs=[inp("Austin", True, "none")], current=True, include_actions=["web_search"], include_caps=["retrieve_current_information"])),
    case("taskframe_travel_advisory_001", "current_fact", "Are there current travel advisories for US travelers to Brazil?", expected(final=["travel", "Brazil"], inputs=[inp("travel", True, "none")], current=True, include_actions=["web_search"], include_caps=["retrieve_current_information"])),

    case("taskframe_bigquery_sql_001", "code_generation", "Write a BigQuery SQL query that returns revenue by month from orders(order_date, amount).", expected(final=["SQL", "revenue"], inputs=[inp("SQL", True, "none")], current=False, include_actions=["none"], include_caps=["generate_code"])),
    case("taskframe_graphql_mutation_001", "code_generation", "Write a GraphQL mutation for updating a user's display name.", expected(final=["GraphQL", "mutation"], inputs=[inp("GraphQL", True, "none")], current=False, include_actions=["none"], include_caps=["generate_code"])),
    case("taskframe_regex_slug_001", "code_generation", "Write a regex that matches slugs like launch-plan-2026.", expected(final=["regex", "slugs"], inputs=[inp("slugs", True, "none")], current=False, include_actions=["none"], include_caps=["generate_code"])),
    case("taskframe_ts_function_001", "code_generation", "Write a TypeScript function isSlug(value: string) that validates lowercase URL slugs.", expected(final=["TypeScript", "isSlug"], inputs=[inp("isSlug", True, "none")], current=False, include_actions=["none"], include_caps=["generate_code"])),
    case("taskframe_repo_todos_001", "repo_search", "Scan this repository for TODO comments and summarize them.", expected(final=["TODO", "repository"], inputs=[inp("repository", True, "file_path")], current=False, include_actions=["file_reading"], include_caps=["search_provided_files"]), attachments=[{"name": "repository files", "format": "file_path", "available": True}]),
    case("taskframe_repo_config_001", "repo_search", "Find deprecated config keys in this codebase.", expected(final=["deprecated", "config"], inputs=[inp("codebase", True, "file_path")], current=False, include_actions=["file_reading"], include_caps=["search_provided_files"]), attachments=[{"name": "repository files", "format": "file_path", "available": True}]),
    case("taskframe_code_edit_auth_001", "code_task", "In src/auth.ts, fix the token refresh bug.", expected(final=["fix", "token"], inputs=[inp("src/auth.ts", True, "file_path")], current=False, include_actions=["file_reading", "file_writing"], include_caps=["inspect_existing_code", "modify_code"], precede=[{"before": "inspect", "after": "modify"}]), attachments=[{"name": "src/auth.ts", "format": "file_path", "available": True}]),
    case("taskframe_code_tests_001", "code_task", "Run the failing tests for tests/test_api.py and fix the parser issue.", expected(final=["failing tests", "parser"], inputs=[inp("tests/test_api.py", True, "file_path")], current=False, include_actions=["file_reading", "file_writing", "code_execution"], include_caps=["inspect_existing_code", "modify_code"], alt_caps=["validate_output_against_requirements"]), attachments=[{"name": "tests/test_api.py", "format": "file_path", "available": True}]),

    case("taskframe_image_alt_001", "image_understanding", "Write concise alt text for this chart image.", expected(final=["alt text", "chart"], inputs=[inp("chart", True, "image")], current=False, include_actions=["image_understanding"], include_caps=["interpret_image_content"]), attachments=[{"name": "chart.png", "format": "image", "available": True}]),
    case("taskframe_image_receipt_001", "image_understanding", "Read the merchant, date, and total from this receipt image.", expected(final=["merchant", "total"], inputs=[inp("receipt", True, "image")], current=False, include_actions=["image_understanding"], include_caps=["extract_information_from_image"]), attachments=[{"name": "receipt.jpg", "format": "image", "available": True}]),
    case("taskframe_image_remove_bg_001", "image_edit", "Remove the background from this headshot.", expected(final=["remove", "background"], inputs=[inp("headshot", True, "image")], current=False, include_actions=["image_understanding", "image_generation"], include_caps=["transform_image"], precede=[{"before": "interpret", "after": "transform"}]), attachments=[{"name": "headshot.png", "format": "image", "available": True}]),
    case("taskframe_image_measure_001", "unsupported_missing_scale", "Measure the real-world width of the table in this image.", expected(final=["measure", "width"], inputs=[inp("image", True, "image"), inp("scale", False, "unknown")], missing=["scale"], current=False, include_actions=["user_input"], include_caps=["request_missing_input"]), attachments=[{"name": "table.jpg", "format": "image", "available": True}]),
    case("taskframe_image_poster_001", "image_generation", "Create a poster graphic for a volunteer orientation with green and white colors.", expected(final=["poster", "volunteer"], inputs=[inp("volunteer", True, "none")], current=False, include_actions=["image_generation"], include_caps=["generate_image"])),
    case("taskframe_pdf_summary_001", "attached_document", "Summarize the attached legal memo and list open questions.", expected(final=["summarize", "legal"], inputs=[inp("memo", True, "pdf")], current=False, include_actions=["file_reading"], include_caps=["extract_information_from_attached_document"], alt_caps=["summarize_document"], precede=[{"before": "extract", "after": "summarize"}]), attachments=[{"name": "legal_memo.pdf", "format": "pdf", "available": True}]),
    case("taskframe_pdf_invoice_001", "attached_document", "Calculate subtotal and tax from the attached invoice PDF.", expected(final=["subtotal", "tax"], inputs=[inp("invoice", True, "pdf")], current=False, include_actions=["file_reading", "calculation"], include_caps=["compute_numeric_result"]), attachments=[{"name": "invoice.pdf", "format": "pdf", "available": True}]),
    case("taskframe_merge_pdfs_001", "file_task", "Merge the attached PDFs into final_packet.pdf.", expected(final=["merge", "PDFs"], inputs=[inp("PDF", True, "pdf")], current=False, include_actions=["file_reading", "file_writing"], include_caps=["combine_files"], precede=[{"before": "extract", "after": "combine"}]), attachments=[{"name": "a.pdf", "format": "pdf", "available": True}, {"name": "b.pdf", "format": "pdf", "available": True}, {"name": "final_packet.pdf", "format": "file_path", "available": True}]),
    case("taskframe_local_file_summary_001", "file_task", "Summarize docs/runbook.md and list risky steps.", expected(final=["summarize", "runbook"], inputs=[inp("docs/runbook.md", True, "file_path")], current=False, include_actions=["file_reading"], include_caps=["extract_information_from_file"]), attachments=[{"name": "docs/runbook.md", "format": "file_path", "available": True}]),
    case("taskframe_write_status_file_001", "file_task", "Create docs/status.md from these notes: rollout green, support staffed, billing watch continues.", expected(final=["status", "notes"], inputs=[inp("notes", True, "pasted_text"), inp("docs/status.md", True, "file_path")], current=False, include_actions=["file_writing"], include_caps=["write_file"]), attachments=[{"name": "docs/status.md", "format": "file_path", "available": True}]),

    case("taskframe_arithmetic_001", "calculation", "What is 9 * 8 - 14?", expected(final=["9", "14"], inputs=[inp("numeric", True, "none")], current=False, include_actions=["calculation"], include_caps=["compute_numeric_result"])),
    case("taskframe_status_email_001", "text_generation", "Draft a short status email saying migration finished and monitoring continues.", expected(final=["status email", "migration"], inputs=[inp("requirements", True, "none")], current=False, include_actions=["none"], include_caps=["draft_text"])),
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        for row in CASES:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"wrote {len(CASES)} cases to {OUT}")


if __name__ == "__main__":
    main()
