#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from generate_capability_holdout import case, expected, inp


OUT = Path("data/capability_planning/near_holdout_50.jsonl")


CASES = [
    case(
        "near_missing_linkedin_bio_001",
        "missing_input",
        "Can you polish my LinkedIn bio?",
        expected(
            final=["polish", "LinkedIn bio"],
            inputs=[inp("LinkedIn bio", False, "unknown")],
            missing=["LinkedIn bio"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["web_search", "file_reading"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_grant_intro_001",
        "missing_input",
        "Revise my grant proposal intro so it is clearer.",
        expected(
            final=["revise", "grant proposal"],
            inputs=[inp("grant proposal", False, "unknown")],
            missing=["grant proposal"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_revenue_plot_001",
        "missing_input",
        "Plot revenue by region for Q2.",
        expected(
            final=["plot", "revenue"],
            inputs=[inp("revenue data", False, "unknown")],
            missing=["revenue"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_survey_dashboard_001",
        "missing_input",
        "Create a dashboard from the survey results.",
        expected(
            final=["dashboard", "survey"],
            inputs=[inp("survey", False, "unknown")],
            missing=["survey"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_blog_post_001",
        "missing_input",
        "Summarize this blog post in five bullets.",
        expected(
            final=["summarize", "blog post"],
            inputs=[inp("blog post", False, "unknown")],
            missing=["blog post"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["web_search"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_transcript_todos_001",
        "missing_input",
        "Pull todos from the customer interview transcript.",
        expected(
            final=["todos", "transcript"],
            inputs=[inp("transcript", False, "unknown")],
            missing=["transcript"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_uploaded_photo_001",
        "missing_input",
        "Describe the product photo I uploaded.",
        expected(
            final=["describe", "photo"],
            inputs=[inp("photo", False, "unknown")],
            missing=["photo"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["image_understanding"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_missing_signup_graph_001",
        "missing_input",
        "Graph monthly signups by acquisition channel.",
        expected(
            final=["graph", "signups"],
            inputs=[inp("signup data", False, "unknown")],
            missing=["signups"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_pasted_todos_001",
        "pasted_text_analysis",
        "Pull todos from these meeting notes:\n\nSam owns the launch email. Rae will confirm budget. Priya needs to book QA time.",
        expected(
            final=["todos", "meeting notes"],
            inputs=[inp("meeting notes", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "near_pasted_followups_001",
        "pasted_text_analysis",
        "List follow-ups from these notes:\n\nLegal needs a revised clause. Finance asked for the forecast. Ops will confirm staffing.",
        expected(
            final=["follow-ups", "notes"],
            inputs=[inp("notes", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "near_pasted_owners_due_dates_001",
        "pasted_text_analysis",
        "Extract owners and due dates from this status note:\n\nMina sends the brief by July 9. Omar updates pricing by July 12.",
        expected(
            final=["owners", "due dates"],
            inputs=[inp("status note", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "near_pasted_linkedin_bio_001",
        "pasted_text_transform",
        "Make this LinkedIn bio tighter: Operations leader with experience helping cross-functional teams improve process, reporting, and vendor management.",
        expected(
            final=["LinkedIn bio", "tighter"],
            inputs=[inp("LinkedIn bio", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["revise_text_for_clarity"],
        ),
    ),
    case(
        "near_translate_spanish_001",
        "pasted_text_transform",
        "Translate this message into Spanish: Please send the signed agreement before noon tomorrow.",
        expected(
            final=["translate", "Spanish"],
            inputs=[inp("message", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["translate_text"],
        ),
    ),
    case(
        "near_markdown_table_entries_001",
        "pasted_text_transform",
        "Turn these entries into a Markdown table: Iris | finance | approved; Jon | legal | pending; Kai | ops | blocked.",
        expected(
            final=["Markdown table"],
            inputs=[inp("entries", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["transform_text_format"],
        ),
    ),
    case(
        "near_compare_three_descriptions_001",
        "pasted_text_analysis",
        "Compare these three feature blurbs and pick the clearest.\n\nA: Dashboards for operators.\n\nB: Reconcile vendor metrics without spreadsheets.\n\nC: See every approval in one queue.",
        expected(
            final=["compare", "blurbs"],
            inputs=[inp("feature blurbs", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["compare_texts"],
        ),
    ),
    case(
        "near_tsv_calc_001",
        "structured_data",
        "From this TSV, calculate total signups by channel:\nchannel\tsignups\nPaid\t80\nOrganic\t75\nReferral\t40",
        expected(
            final=["calculate", "signups"],
            inputs=[inp("TSV", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "near_semicolon_data_001",
        "structured_data",
        "From this data, compute average score by team:\nteam;score\nA;81\nB;92\nA;87",
        expected(
            final=["compute", "average score"],
            inputs=[inp("data", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "near_pipe_table_calc_001",
        "structured_data",
        "From this table, calculate total hours by project:\nproject|hours\nApollo|4\nBeacon|6\nApollo|3",
        expected(
            final=["calculate", "hours"],
            inputs=[inp("table", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "near_json_admins_001",
        "structured_data",
        "From this JSON, list admin users: [{\"name\":\"Nia\",\"role\":\"admin\"},{\"name\":\"Sol\",\"role\":\"viewer\"},{\"name\":\"Uma\",\"role\":\"admin\"}]",
        expected(
            final=["list", "admin"],
            inputs=[inp("JSON", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "near_csv_without_colon_001",
        "structured_data",
        "Here is CSV data. Count orders by status.\nstatus,orders\nOpen,12\nClosed,18\nOpen,5",
        expected(
            final=["count", "orders"],
            inputs=[inp("CSV", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "near_pasted_table_revenue_001",
        "structured_data",
        "Given this pasted table, calculate revenue by region:\nregion,revenue\nEast,200\nWest,150\nEast,100",
        expected(
            final=["calculate", "revenue"],
            inputs=[inp("table", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "near_compare_three_links_001",
        "url",
        "Compare these three pages: https://example.com/a https://example.com/b https://example.com/c",
        expected(
            final=["compare", "pages"],
            inputs=[inp("https://example.com/a", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            alt_caps=["compare_texts"],
            precede=[{"before": "retrieve", "after": "compare"}],
        ),
    ),
    case(
        "near_contrast_two_urls_001",
        "url",
        "Contrast the onboarding docs at https://docs.example.com/basic and https://docs.example.com/enterprise.",
        expected(
            final=["contrast", "onboarding"],
            inputs=[inp("docs.example.com", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            precede=[{"before": "retrieve", "after": "compare"}],
        ),
    ),
    case(
        "near_single_url_summary_001",
        "url",
        "Summarize https://example.org/blog/process-metrics in four bullets.",
        expected(
            final=["summarize", "process metrics"],
            inputs=[inp("https://example.org/blog/process-metrics", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            alt_caps=["summarize_document"],
            precede=[{"before": "retrieve", "after": "summarize"}],
        ),
    ),
    case(
        "near_url_release_extract_001",
        "url",
        "Extract migration steps from https://example.com/releases/v3.",
        expected(
            final=["extract", "migration"],
            inputs=[inp("https://example.com/releases/v3", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
        ),
    ),
    case(
        "near_fact_check_retirement_001",
        "fact_checking",
        "Verify whether the current mayor of Chicago announced a transit plan this week.",
        expected(
            final=["verify", "transit plan"],
            inputs=[inp("Chicago mayor transit plan", True, "none")],
            current=True,
            include_actions=["web_search", "fact_checking"],
            include_caps=["verify_current_information"],
            precede=[{"before": "verify", "after": "answer"}],
        ),
    ),
    case(
        "near_postgres_query_001",
        "generic_coding_parameters",
        "Write a Postgres query that returns monthly revenue from orders(created_at, total).",
        expected(
            final=["Postgres query", "revenue"],
            inputs=[inp("orders created_at total", True, "none")],
            current=False,
            include_actions=["none"],
            exclude_actions=["file_reading", "user_input"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "near_react_component_001",
        "generic_coding_parameters",
        "Write a React component StatusPill({status}) that renders active as green and blocked as red.",
        expected(
            final=["React component", "StatusPill"],
            inputs=[inp("StatusPill", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "near_bash_script_001",
        "generic_coding_parameters",
        "Write a bash script that prints the five largest files under a directory path.",
        expected(
            final=["bash script", "largest files"],
            inputs=[inp("script", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "near_select_statement_001",
        "generic_coding_parameters",
        "Return a SELECT statement for users(id, plan) that counts users by plan.",
        expected(
            final=["SELECT", "users"],
            inputs=[inp("users id plan", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "near_prisma_schema_001",
        "generic_coding_parameters",
        "Generate a Prisma schema for Customer and Invoice models.",
        expected(
            final=["Prisma schema", "Customer"],
            inputs=[inp("Prisma schema", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "near_generic_function_001",
        "generic_coding_parameters",
        "Write a function longestRun(values) that returns the length of the longest repeated-value streak.",
        expected(
            final=["function", "longestRun"],
            inputs=[inp("longestRun", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "near_repo_deprecated_apis_001",
        "file_reading",
        "Scan this codebase for deprecated API calls and summarize the files affected.",
        expected(
            final=["scan", "deprecated API"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
            precede=[{"before": "search", "after": "summarize"}],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "near_repo_oldauth_usages_001",
        "file_reading",
        "Find usages of oldAuth in the repo and write a migration note.",
        expected(
            final=["find", "oldAuth"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
            precede=[{"before": "search", "after": "report"}],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "near_repo_feature_flag_refs_001",
        "file_reading",
        "Search for references to ENABLE_BILLING_V2 in this repository.",
        expected(
            final=["search", "ENABLE_BILLING_V2"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "near_repo_todos_001",
        "file_reading",
        "Find TODOs in the codebase related to payments.",
        expected(
            final=["Find", "TODOs"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "near_repo_console_logs_001",
        "file_reading",
        "Search the codebase for console.log calls and make a cleanup list.",
        expected(
            final=["Search", "console.log"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
            precede=[{"before": "search", "after": "report"}],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "near_image_alt_001",
        "image_understanding",
        "Write alt text for the attached product dashboard screenshot.",
        expected(
            final=["alt text", "dashboard"],
            inputs=[inp("dashboard screenshot", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding"],
            include_caps=["interpret_image_content"],
        ),
        [{"name": "dashboard_screenshot.png", "format": "image", "available": True}],
    ),
    case(
        "near_missing_uploaded_image_001",
        "missing_input",
        "Tell me what is happening in the screenshot I uploaded.",
        expected(
            final=["screenshot", "happening"],
            inputs=[inp("screenshot", False, "unknown")],
            missing=["screenshot"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["image_understanding"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "near_image_measure_scale_001",
        "unsupported_missing_scale",
        "Measure the real-world height of the lamp in the attached photo.",
        expected(
            final=["measure", "lamp"],
            inputs=[inp("photo", True, "image"), inp("scale", False, "unknown")],
            missing=["scale"],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding", "user_input"],
            include_caps=["request_missing_input"],
            precede=[{"before": "request_missing_input", "after": "measure"}],
        ),
        [{"name": "lamp.jpg", "format": "image", "available": True}],
    ),
    case(
        "near_image_remove_background_001",
        "image_editing",
        "Remove the background from the attached headshot.",
        expected(
            final=["remove", "background"],
            inputs=[inp("headshot", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_generation"],
            include_caps=["transform_image"],
        ),
        [{"name": "headshot.png", "format": "image", "available": True}],
    ),
    case(
        "near_current_node_lts_001",
        "current_facts",
        "What is the latest Node.js LTS version?",
        expected(
            final=["latest", "Node"],
            inputs=[inp("Node", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "near_current_ceo_001",
        "current_facts",
        "Who is the current CEO of AMD?",
        expected(
            final=["current", "CEO"],
            inputs=[inp("AMD CEO", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "near_weather_tomorrow_001",
        "current_facts",
        "Will it rain in Denver tomorrow morning?",
        expected(
            final=["rain", "Denver"],
            inputs=[inp("Denver", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "near_stock_msft_001",
        "current_facts",
        "What is MSFT trading at right now?",
        expected(
            final=["MSFT", "trading"],
            inputs=[inp("MSFT", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "near_write_status_file_001",
        "file_writing",
        "Create docs/status.md from this update: rollout is green, legal review is done, training starts Friday.",
        expected(
            final=["create", "status"],
            inputs=[inp("docs/status.md", True, "file_path"), inp("update", True, "pasted_text")],
            include_formats=["file_path", "pasted_text"],
            current=False,
            include_actions=["file_writing"],
            include_caps=["write_file"],
        ),
        [{"name": "docs/status.md", "format": "file_path", "available": True}],
    ),
    case(
        "near_merge_three_pdfs_001",
        "file_merge",
        "Merge the attached PDFs into one appendix packet.",
        expected(
            final=["merge", "PDFs"],
            inputs=[inp("appendix_a.pdf", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading", "file_writing"],
            include_caps=["combine_files"],
        ),
        [
            {"name": "appendix_a.pdf", "format": "pdf", "available": True},
            {"name": "appendix_b.pdf", "format": "pdf", "available": True},
            {"name": "appendix_c.pdf", "format": "pdf", "available": True},
        ],
    ),
    case(
        "near_pdf_extract_risks_001",
        "attached_pdf",
        "Extract risks and owners from the attached implementation plan PDF.",
        expected(
            final=["extract", "risks"],
            inputs=[inp("implementation plan", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_attached_document"],
        ),
        [{"name": "implementation_plan.pdf", "format": "pdf", "available": True}],
    ),
    case(
        "near_local_file_flags_001",
        "file_path_reading",
        "Read configs/staging.yaml and summarize the enabled feature flags.",
        expected(
            final=["read", "feature flags"],
            inputs=[inp("configs/staging.yaml", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_file"],
            precede=[{"before": "extract", "after": "summarize"}],
        ),
        [{"name": "configs/staging.yaml", "format": "file_path", "available": True}],
    ),
    case(
        "near_spreadsheet_growth_001",
        "attached_spreadsheet",
        "Use the attached spreadsheet to calculate growth by product line.",
        expected(
            final=["calculate", "growth"],
            inputs=[inp("spreadsheet", True, "attached_file")],
            include_formats=["attached_file"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["analyze_provided_dataset"],
            precede=[{"before": "extract", "after": "calculate"}],
        ),
        [{"name": "product_growth.xlsx", "format": "attached_file", "available": True}],
    ),
]


def main() -> None:
    if len(CASES) != 50:
        raise SystemExit(f"expected 50 near-holdout cases, found {len(CASES)}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        for index, row in enumerate(CASES):
            row = {"row_index": index, **row}
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    print(f"wrote {len(CASES)} cases to {OUT}")


if __name__ == "__main__":
    main()
