#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


OUT = Path("data/capability_planning/holdout_50.jsonl")


def expected(
    *,
    final: list[str] | None = None,
    inputs: list[dict[str, Any]] | None = None,
    missing: list[str] | None = None,
    include_formats: list[str] | None = None,
    exclude_formats: list[str] | None = None,
    current: bool | None = None,
    include_actions: list[str] | None = None,
    exclude_actions: list[str] | None = None,
    include_caps: list[str] | None = None,
    alt_caps: list[str] | None = None,
    exclude_caps: list[str] | None = None,
    precede: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    return {
        "run1": {
            **({"final_intent_keywords": final} if final else {}),
            **({"inputs": inputs} if inputs else {}),
            **({"missing_input_keywords": missing} if missing else {}),
            **({"must_include_format": include_formats} if include_formats else {}),
            **({"must_not_include_format": exclude_formats} if exclude_formats else {}),
        },
        "run2": {
            **({"needs_current_or_external_info": current} if current is not None else {}),
            **({"must_include_external_action_type": include_actions} if include_actions else {}),
            **({"must_not_include_external_action_type": exclude_actions} if exclude_actions else {}),
        },
        "run3": {
            **({"must_include_capability": include_caps} if include_caps else {}),
            **({"must_include_capability_alt": alt_caps} if alt_caps else {}),
            **({"must_not_include_capability": exclude_caps} if exclude_caps else {}),
            **({"must_include_external_action_type": include_actions} if include_actions else {}),
            **({"must_not_include_external_action_type": exclude_actions} if exclude_actions else {}),
        },
        "graph": {"must_precede": precede or []},
    }


def inp(keyword: str, available: bool, fmt: str) -> dict[str, Any]:
    return {"keyword": keyword, "available": available, "format": fmt}


def case(
    id_: str,
    category: str,
    request: str,
    exp: dict[str, Any],
    attachments: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    row = {
        "id": id_,
        "category": category,
        "request": request,
        "expected": exp,
    }
    if attachments is not None:
        row["attachments_metadata"] = attachments
    return row


CASES = [
    case(
        "holdout_pasted_revision_001",
        "pasted_text_transform",
        "Polish this customer note so it sounds professional:\n\nwe shipped late and the client is annoyed but we can fix it by friday.",
        expected(
            final=["polish", "customer note"],
            inputs=[inp("customer note", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["revise_text_for_clarity"],
        ),
    ),
    case(
        "holdout_translate_french_001",
        "pasted_text_transform",
        "Translate this paragraph into French: The office will be closed Monday for maintenance and will reopen Tuesday morning.",
        expected(
            final=["translate", "French"],
            inputs=[inp("paragraph", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["translate_text"],
            exclude_caps=["request_missing_input"],
        ),
    ),
    case(
        "holdout_markdown_table_001",
        "pasted_text_transform",
        "Turn this list into a Markdown table: Nora - finance - starts July; Eli - design - starts August; Sam - ops - starts September.",
        expected(
            final=["Markdown table"],
            inputs=[inp("list", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["transform_text_format"],
        ),
    ),
    case(
        "holdout_compare_copy_001",
        "pasted_text_analysis",
        "Compare these two homepage headlines and say which is clearer.\n\nA: Build better internal workflows faster.\n\nB: Give operations teams one place to automate approvals, reminders, and handoffs.",
        expected(
            final=["compare", "headlines"],
            inputs=[inp("headlines", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["compare_texts"],
        ),
    ),
    case(
        "holdout_sentiment_tickets_001",
        "pasted_text_analysis",
        "Classify these support tickets as urgent, normal, or low priority:\n1. Checkout is down for all users.\n2. Please change my billing email.\n3. The icon color looks odd.",
        expected(
            final=["classify", "support tickets"],
            inputs=[inp("support tickets", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["classify_provided_text"],
        ),
    ),
    case(
        "holdout_error_log_001",
        "pasted_text_analysis",
        "Explain this stack trace and suggest the likely fix:\n\nTypeError: cannot read properties of undefined (reading 'items') at src/cart.ts:42",
        expected(
            final=["explain", "stack trace"],
            inputs=[inp("stack trace", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "holdout_pasted_action_items_001",
        "pasted_text_analysis",
        "Extract the action items from these meeting notes:\n\nPriya will update the launch checklist. Omar needs to confirm pricing. Legal asked for one more review.",
        expected(
            final=["extract", "action items"],
            inputs=[inp("meeting notes", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "holdout_rewrite_tone_001",
        "pasted_text_transform",
        "Make this message warmer but still concise:\n\nYour request was denied because the submitted receipts were incomplete.",
        expected(
            final=["warmer", "message"],
            inputs=[inp("message", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["revise_text_for_clarity"],
        ),
    ),
    case(
        "holdout_missing_resume_001",
        "missing_input",
        "Can you improve my resume summary?",
        expected(
            final=["improve", "resume"],
            inputs=[inp("resume", False, "unknown")],
            missing=["resume"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "holdout_missing_chart_data_001",
        "missing_input",
        "Make a chart of inventory counts by warehouse.",
        expected(
            final=["chart", "inventory"],
            inputs=[inp("inventory data", False, "unknown")],
            missing=["inventory"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
            exclude_actions=["web_search"],
        ),
    ),
    case(
        "holdout_missing_deck_001",
        "missing_input",
        "Summarize the slide deck I attached and list the risks.",
        expected(
            final=["summarize", "slide deck"],
            inputs=[inp("slide deck", False, "unknown")],
            missing=["slide deck"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "holdout_missing_screenshot_001",
        "missing_input",
        "Write alt text for the screenshot I attached.",
        expected(
            final=["alt text", "screenshot"],
            inputs=[inp("screenshot", False, "unknown")],
            missing=["screenshot"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["image_understanding", "file_reading"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "holdout_missing_article_text_001",
        "missing_input",
        "Summarize this article in three bullets.",
        expected(
            final=["summarize", "article"],
            inputs=[inp("article", False, "unknown")],
            missing=["article"],
            current=False,
            include_actions=["user_input"],
            exclude_actions=["web_search", "file_reading"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "holdout_current_weather_001",
        "current_facts",
        "What is the weather in Seattle tomorrow morning?",
        expected(
            final=["weather", "Seattle"],
            inputs=[inp("Seattle weather", True, "none")],
            current=True,
            include_actions=["web_search"],
            exclude_actions=["file_reading"],
            include_caps=["retrieve_current_information"],
            precede=[{"before": "retrieve", "after": "answer"}],
        ),
    ),
    case(
        "holdout_current_exchange_rate_001",
        "current_facts",
        "What is today's USD to EUR exchange rate?",
        expected(
            final=["today", "exchange rate"],
            inputs=[inp("USD to EUR", True, "none")],
            current=True,
            include_actions=["web_search"],
            exclude_actions=["file_reading"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "holdout_current_ceo_001",
        "current_facts",
        "Who is the current CEO of Nvidia?",
        expected(
            final=["current", "CEO"],
            inputs=[inp("Nvidia CEO", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "holdout_latest_react_version_001",
        "current_facts",
        "What is the latest stable version of React?",
        expected(
            final=["latest", "React"],
            inputs=[inp("React version", True, "none")],
            current=True,
            include_actions=["web_search"],
            exclude_actions=["file_reading"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "holdout_current_mortgage_rates_001",
        "current_facts",
        "What are current 30-year mortgage rates in the US?",
        expected(
            final=["current", "mortgage rates"],
            inputs=[inp("mortgage rates", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "holdout_stock_tesla_001",
        "current_facts",
        "What is Tesla's latest stock price and market cap?",
        expected(
            final=["latest", "stock price"],
            inputs=[inp("Tesla stock price market cap", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "holdout_fact_check_policy_001",
        "fact_checking",
        "Fact-check whether the current governor of California signed a new housing bill this month.",
        expected(
            final=["fact check", "housing bill"],
            inputs=[inp("California governor housing bill", True, "none")],
            current=True,
            include_actions=["web_search", "fact_checking"],
            include_caps=["verify_current_information"],
            precede=[{"before": "verify", "after": "answer"}],
        ),
    ),
    case(
        "holdout_latest_guidance_001",
        "current_facts",
        "What is the latest CDC guidance on flu isolation?",
        expected(
            final=["latest", "CDC guidance"],
            inputs=[inp("CDC flu guidance", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "holdout_url_article_001",
        "url",
        "Summarize the article at https://example.org/ops-research and list four implications.",
        expected(
            final=["summarize", "article"],
            inputs=[inp("https://example.org/ops-research", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            alt_caps=["summarize_document"],
            precede=[{"before": "retrieve", "after": "summarize"}],
        ),
    ),
    case(
        "holdout_url_two_sources_001",
        "url",
        "Compare the pricing pages at https://example.com/basic and https://example.com/pro.",
        expected(
            final=["compare", "pricing"],
            inputs=[inp("https://example.com/basic", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            precede=[{"before": "retrieve", "after": "compare"}],
        ),
    ),
    case(
        "holdout_youtube_001",
        "url",
        "Summarize the main argument in this video: https://youtube.com/watch?v=holdout123",
        expected(
            final=["summarize", "video"],
            inputs=[inp("youtube.com", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
        ),
    ),
    case(
        "holdout_pdf_contract_001",
        "attached_pdf",
        "From the attached contract, extract the termination clause and renewal dates.",
        expected(
            final=["extract", "termination clause"],
            inputs=[inp("contract", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading"],
            exclude_actions=["web_search"],
            include_caps=["extract_information_from_attached_document"],
        ),
        [{"name": "vendor_contract.pdf", "format": "pdf", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_pdf_summary_001",
        "attached_pdf",
        "Summarize the attached annual report and call out financial risks.",
        expected(
            final=["summarize", "annual report"],
            inputs=[inp("annual report", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_attached_document"],
            alt_caps=["summarize_document"],
            precede=[{"before": "extract", "after": "summarize"}],
        ),
        [{"name": "annual_report.pdf", "format": "pdf", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_pdf_invoice_calc_001",
        "pdf_calculation",
        "From the attached receipt PDF, compute the total reimbursable amount before tips.",
        expected(
            final=["compute", "total"],
            inputs=[inp("receipt", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["extract_information_from_attached_document"],
            alt_caps=["compute_numeric_result"],
            precede=[{"before": "extract", "after": "compute"}],
        ),
        [{"name": "trip_receipts.pdf", "format": "pdf", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_docx_extract_001",
        "attached_file",
        "Extract milestones, owners, and blockers from the attached launch plan document.",
        expected(
            final=["extract", "milestones"],
            inputs=[inp("launch plan", True, "attached_file")],
            include_formats=["attached_file"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_attached_document"],
        ),
        [{"name": "launch_plan.docx", "format": "attached_file", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_slides_summary_001",
        "attached_file",
        "Summarize the attached board deck and identify decisions needed.",
        expected(
            final=["summarize", "board deck"],
            inputs=[inp("board deck", True, "attached_file")],
            include_formats=["attached_file"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_attached_document"],
            alt_caps=["summarize_document"],
        ),
        [{"name": "board_deck.pptx", "format": "attached_file", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_csv_median_001",
        "attached_structured_data",
        "Analyze the attached CSV of orders and compute median order value by channel.",
        expected(
            final=["analyze", "orders"],
            inputs=[inp("CSV", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["analyze_provided_dataset"],
            precede=[{"before": "extract", "after": "analyze"}],
        ),
        [{"name": "orders.csv", "format": "structured_data", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_xlsx_pivot_001",
        "attached_spreadsheet",
        "In the attached workbook, calculate quarterly churn by segment and flag outliers.",
        expected(
            final=["calculate", "churn"],
            inputs=[inp("workbook", True, "attached_file")],
            include_formats=["attached_file"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["analyze_provided_dataset"],
            precede=[{"before": "extract", "after": "calculate"}],
        ),
        [{"name": "churn_by_segment.xlsx", "format": "attached_file", "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_local_file_summary_001",
        "file_path_reading",
        "Read ./notes/customer_interviews.md and summarize the top complaints.",
        expected(
            final=["read", "summarize"],
            inputs=[inp("customer_interviews.md", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_file"],
            precede=[{"before": "extract", "after": "summarize"}],
        ),
        [{"name": "./notes/customer_interviews.md", "format": "file_path", "available": True, "contents_in_context": False}],
    ),
    case(
        "holdout_repo_search_001",
        "file_reading",
        "Find all FIXME comments in this repository and write a short cleanup report.",
        expected(
            final=["find", "FIXME", "report"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
            precede=[{"before": "search", "after": "report"}],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "holdout_merge_pdfs_001",
        "file_read_write",
        "Merge the three attached PDFs into one packet named onboarding_packet.pdf.",
        expected(
            final=["merge", "PDFs"],
            inputs=[inp("attached PDFs", True, "pdf"), inp("onboarding_packet.pdf", True, "file_path")],
            include_formats=["pdf", "file_path"],
            current=False,
            include_actions=["file_reading", "file_writing"],
            include_caps=["combine_files"],
            precede=[{"before": "read", "after": "write"}],
        ),
        [
            {"name": "welcome.pdf", "format": "pdf", "available": True},
            {"name": "benefits.pdf", "format": "pdf", "available": True},
            {"name": "policies.pdf", "format": "pdf", "available": True},
            {"name": "onboarding_packet.pdf", "format": "file_path", "available": True},
        ],
    ),
    case(
        "holdout_code_fix_001",
        "code_file_read_write",
        "In src/math_utils.py, fix the rounding bug and add tests in tests/test_math_utils.py.",
        expected(
            final=["fix", "rounding bug", "tests"],
            inputs=[inp("src/math_utils.py", True, "file_path"), inp("test_math_utils", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading", "file_writing", "code_execution"],
            exclude_actions=["web_search"],
            include_caps=["inspect_existing_code"],
            alt_caps=["modify_code"],
            precede=[{"before": "inspect", "after": "modify"}, {"before": "modify", "after": "test"}],
        ),
        [{"name": "src/math_utils.py", "format": "file_path", "available": True}, {"name": "tests/test_math_utils.py", "format": "file_path", "available": True}],
    ),
    case(
        "holdout_code_cli_001",
        "code_file_read_write",
        "Add a --dry-run flag to src/cli.py and update tests for the new behavior.",
        expected(
            final=["add", "dry-run"],
            inputs=[inp("src/cli.py", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading", "file_writing", "code_execution"],
            include_caps=["modify_code"],
            precede=[{"before": "inspect", "after": "modify"}],
        ),
        [{"name": "src/cli.py", "format": "file_path", "available": True}, {"name": "tests/test_cli.py", "format": "file_path", "available": True}],
    ),
    case(
        "holdout_code_run_first_001",
        "code_execution",
        "Run the test suite, fix failing imports in app/__init__.py, and summarize what changed.",
        expected(
            final=["run", "test", "fix"],
            inputs=[inp("app/__init__.py", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["code_execution", "file_reading", "file_writing"],
            include_caps=["execute_code"],
            alt_caps=["modify_code"],
            precede=[{"before": "execute", "after": "modify"}, {"before": "modify", "after": "validate"}],
        ),
        [{"name": "app/__init__.py", "format": "file_path", "available": True}, {"name": "tests/", "format": "file_path", "available": True}],
    ),
    case(
        "holdout_generic_function_001",
        "generic_coding_parameters",
        "Write a Python function longest_unique_subarray(nums, limit) that returns the longest contiguous slice with all values <= limit.",
        expected(
            final=["write", "function"],
            inputs=[inp("nums limit", True, "none")],
            current=False,
            include_actions=["none"],
            exclude_actions=["file_reading", "user_input", "web_search"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "holdout_sql_generation_001",
        "generic_coding_parameters",
        "Write a SQL query that returns the top 10 customers by total spend from orders(customer_id, amount).",
        expected(
            final=["write", "SQL query"],
            inputs=[inp("orders customer_id amount", True, "none")],
            current=False,
            include_actions=["none"],
            exclude_actions=["file_reading", "user_input"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "holdout_image_alt_001",
        "image_understanding",
        "Write concise alt text for the attached dashboard screenshot.",
        expected(
            final=["alt text", "screenshot"],
            inputs=[inp("screenshot", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["interpret_image_content"],
        ),
        [{"name": "dashboard.png", "format": "image", "available": True}],
    ),
    case(
        "holdout_image_ocr_001",
        "image_understanding",
        "Read the attached whiteboard photo and list the deadlines.",
        expected(
            final=["read", "whiteboard"],
            inputs=[inp("whiteboard", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding"],
            include_caps=["extract_information_from_image"],
        ),
        [{"name": "whiteboard.jpg", "format": "image", "available": True}],
    ),
    case(
        "holdout_image_edit_001",
        "image_editing",
        "Edit the attached logo to remove the white background and make it transparent.",
        expected(
            final=["edit", "logo"],
            inputs=[inp("logo", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding", "image_generation"],
            include_caps=["transform_image"],
            precede=[{"before": "interpret", "after": "transform"}],
        ),
        [{"name": "logo.png", "format": "image", "available": True}],
    ),
    case(
        "holdout_image_measure_001",
        "unsupported_missing_scale",
        "Measure the real-world width of the table in this image.",
        expected(
            final=["measure", "width"],
            inputs=[inp("image", True, "image"), inp("scale", False, "unknown")],
            missing=["scale"],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding", "user_input"],
            exclude_actions=["web_search"],
            include_caps=["request_missing_input"],
            precede=[{"before": "request_missing_input", "after": "measure"}],
        ),
        [{"name": "table.jpg", "format": "image", "available": True}],
    ),
    case(
        "holdout_image_generation_001",
        "image_generation",
        "Create an image of a simple square app icon for a budgeting app with blue and gold colors.",
        expected(
            final=["create", "app icon"],
            inputs=[inp("budgeting app icon", True, "none")],
            current=False,
            include_actions=["image_generation"],
            exclude_actions=["web_search", "file_reading"],
            include_caps=["generate_image"],
        ),
    ),
    case(
        "holdout_json_sort_001",
        "structured_data",
        'From this JSON, list active accounts sorted by renewal_date ascending: [{"name":"Aster","active":true,"renewal_date":"2026-08-01"},{"name":"Bryn","active":false,"renewal_date":"2026-07-15"},{"name":"Coda","active":true,"renewal_date":"2026-07-20"}]',
        expected(
            final=["list", "active accounts"],
            inputs=[inp("JSON", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["none"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "holdout_inline_csv_calc_001",
        "structured_data",
        "From this CSV, compute total revenue by plan:\nplan,revenue\nBasic,120\nPro,300\nBasic,80",
        expected(
            final=["compute", "revenue"],
            inputs=[inp("CSV", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            exclude_actions=["file_reading", "web_search"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "holdout_calculation_001",
        "calculation",
        "What is 18 + 42 / 7?",
        expected(
            final=["compute", "numeric"],
            inputs=[inp("18 + 42 / 7", True, "none")],
            current=False,
            include_actions=["calculation"],
            exclude_actions=["web_search", "file_reading"],
            include_caps=["compute_numeric_result"],
        ),
    ),
    case(
        "holdout_tax_calc_001",
        "calculation",
        "A monitor costs $249.99 and sales tax is 9.1%. What is the final price?",
        expected(
            final=["final price"],
            inputs=[inp("249.99 9.1", True, "none")],
            current=False,
            include_actions=["calculation"],
            include_caps=["compute_numeric_result"],
        ),
    ),
    case(
        "holdout_write_email_001",
        "text_generation",
        "Write a brief email to Jordan asking to move tomorrow's meeting to 2 pm because the vendor call ran long.",
        expected(
            final=["write", "email"],
            inputs=[inp("Jordan meeting 2 pm", True, "none")],
            current=False,
            include_actions=["none"],
            exclude_actions=["web_search", "file_reading"],
            include_caps=["draft_text"],
        ),
    ),
    case(
        "holdout_write_file_notes_001",
        "file_writing",
        "Create reports/summary.md from these notes: onboarding is delayed, budget is approved, legal review is pending.",
        expected(
            final=["create", "summary"],
            inputs=[inp("notes", True, "pasted_text"), inp("reports/summary.md", True, "file_path")],
            include_formats=["pasted_text", "file_path"],
            current=False,
            include_actions=["file_writing"],
            exclude_actions=["web_search", "file_reading"],
            include_caps=["write_file"],
        ),
        [{"name": "reports/summary.md", "format": "file_path", "available": True}],
    ),
]


def main() -> None:
    if len(CASES) != 50:
        raise SystemExit(f"expected 50 holdout cases, found {len(CASES)}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        for index, row in enumerate(CASES):
            row = {"row_index": index, **row}
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    print(f"wrote {len(CASES)} cases to {OUT}")


if __name__ == "__main__":
    main()
