#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from generate_capability_holdout import case, expected, inp


OUT = Path("data/capability_planning/fresh_holdout_50.jsonl")


CASES = [
    case(
        "fresh_missing_portfolio_blurb_001",
        "missing_input",
        "Can you tighten my portfolio blurb?",
        expected(
            final=["tighten", "portfolio"],
            inputs=[inp("portfolio blurb", False, "unknown")],
            missing=["portfolio"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_abstract_001",
        "missing_input",
        "Rewrite my research abstract to be less wordy.",
        expected(
            final=["rewrite", "abstract"],
            inputs=[inp("abstract", False, "unknown")],
            missing=["abstract"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_expense_chart_001",
        "missing_input",
        "Chart expenses by vendor for May.",
        expected(
            final=["chart", "expenses"],
            inputs=[inp("expense data", False, "unknown")],
            missing=["expense"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_shared_deck_001",
        "missing_input",
        "Summarize the deck I shared and list the asks.",
        expected(
            final=["summarize", "deck"],
            inputs=[inp("deck", False, "unknown")],
            missing=["deck"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_uploaded_contract_001",
        "missing_input",
        "Extract payment terms from the contract I uploaded.",
        expected(
            final=["extract", "payment terms"],
            inputs=[inp("contract", False, "unknown")],
            missing=["contract"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_uploaded_screenshot_001",
        "missing_input",
        "What error is shown in the screenshot I uploaded?",
        expected(
            final=["error", "screenshot"],
            inputs=[inp("screenshot", False, "unknown")],
            missing=["screenshot"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_campaign_results_001",
        "missing_input",
        "Graph campaign results by channel.",
        expected(
            final=["graph", "campaign"],
            inputs=[inp("campaign results", False, "unknown")],
            missing=["campaign"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_missing_customer_quotes_001",
        "missing_input",
        "Summarize the customer quotes into themes.",
        expected(
            final=["summarize", "customer quotes"],
            inputs=[inp("customer quotes", False, "unknown")],
            missing=["quotes"],
            current=False,
            include_actions=["user_input"],
            include_caps=["request_missing_input"],
        ),
    ),
    case(
        "fresh_pasted_next_steps_001",
        "pasted_text_analysis",
        "Find next steps in these planning notes:\n\nAlex drafts the launch email. Bo checks security review. Casey books training.",
        expected(
            final=["next steps", "planning notes"],
            inputs=[inp("planning notes", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "fresh_pasted_decisions_001",
        "pasted_text_analysis",
        "Extract decisions from these workshop notes:\n\nWe will delay beta by one week. Pricing stays unchanged. Support owns rollout comms.",
        expected(
            final=["extract", "decisions"],
            inputs=[inp("workshop notes", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "fresh_compare_subject_lines_001",
        "pasted_text_analysis",
        "Compare these subject lines and choose the clearest.\n\nA: Your dashboard is ready\nB: See this week's metrics in your new dashboard",
        expected(
            final=["compare", "subject lines"],
            inputs=[inp("subject lines", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["compare_texts"],
        ),
    ),
    case(
        "fresh_entries_to_table_001",
        "pasted_text_transform",
        "Turn these bullets into a Markdown table: Alpha - owner Mia - due Friday; Beta - owner Leo - due Monday.",
        expected(
            final=["Markdown table"],
            inputs=[inp("bullets", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["transform_text_format"],
        ),
    ),
    case(
        "fresh_translate_italian_001",
        "pasted_text_transform",
        "Translate this update into Italian: The vendor review is complete and rollout starts next week.",
        expected(
            final=["translate", "Italian"],
            inputs=[inp("update", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["translate_text"],
        ),
    ),
    case(
        "fresh_rewrite_apology_001",
        "pasted_text_transform",
        "Make this apology note more sincere: Sorry for the confusion. We will fix the invoice soon.",
        expected(
            final=["apology", "sincere"],
            inputs=[inp("apology note", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["revise_text_for_clarity"],
        ),
    ),
    case(
        "fresh_classify_bug_reports_001",
        "pasted_text_analysis",
        "Classify these bug reports as frontend, backend, or docs:\n1. Button overlaps text.\n2. API returns 500.\n3. Setup guide is outdated.",
        expected(
            final=["classify", "bug reports"],
            inputs=[inp("bug reports", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["classify_provided_text"],
        ),
    ),
    case(
        "fresh_stack_trace_001",
        "pasted_text_analysis",
        "Explain this traceback:\n\nKeyError: 'customer_id' at sync_orders.py:117 while grouping records.",
        expected(
            final=["explain", "traceback"],
            inputs=[inp("traceback", True, "pasted_text")],
            current=False,
            include_actions=["none"],
            include_caps=["analyze_provided_text"],
        ),
    ),
    case(
        "fresh_semicolon_total_001",
        "structured_data",
        "From this table, compute total cost by team:\nteam;cost\nOps;90\nSales;120\nOps;30",
        expected(
            final=["compute", "cost"],
            inputs=[inp("table", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "fresh_tsv_median_001",
        "structured_data",
        "From this TSV, calculate median handle time by queue:\nqueue\thandle_time\nBilling\t5\nBilling\t7\nSupport\t4",
        expected(
            final=["calculate", "median"],
            inputs=[inp("TSV", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "fresh_pipe_conversion_001",
        "structured_data",
        "From this data, calculate conversion by campaign:\ncampaign|visits|conversions\nA|100|12\nB|80|16",
        expected(
            final=["calculate", "conversion"],
            inputs=[inp("data", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "fresh_json_active_count_001",
        "structured_data",
        "From this JSON, count active users: [{\"name\":\"Ari\",\"active\":true},{\"name\":\"Bea\",\"active\":false},{\"name\":\"Cal\",\"active\":true}]",
        expected(
            final=["count", "active"],
            inputs=[inp("JSON", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
    ),
    case(
        "fresh_url_summary_001",
        "url",
        "Summarize the guide at https://example.com/guides/onboarding.",
        expected(
            final=["summarize", "guide"],
            inputs=[inp("https://example.com/guides/onboarding", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            alt_caps=["summarize_document"],
            precede=[{"before": "retrieve", "after": "summarize"}],
        ),
    ),
    case(
        "fresh_url_differences_001",
        "url",
        "What are the differences between https://example.com/free and https://example.com/team?",
        expected(
            final=["differences", "free"],
            inputs=[inp("https://example.com/free", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            precede=[{"before": "retrieve", "after": "compare"}],
        ),
    ),
    case(
        "fresh_url_three_contrast_001",
        "url",
        "Contrast these sources: https://a.example/report https://b.example/report https://c.example/report",
        expected(
            final=["Contrast", "sources"],
            inputs=[inp("https://a.example/report", True, "url")],
            include_formats=["url"],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_external_information"],
            alt_caps=["compare_texts"],
            precede=[{"before": "retrieve", "after": "compare"}],
        ),
    ),
    case(
        "fresh_latest_django_001",
        "current_facts",
        "What is the latest stable Django version?",
        expected(
            final=["latest", "Django"],
            inputs=[inp("Django", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "fresh_rain_portland_001",
        "current_facts",
        "Is it expected to rain in Portland tomorrow?",
        expected(
            final=["rain", "Portland"],
            inputs=[inp("Portland", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "fresh_current_rate_001",
        "current_facts",
        "What is the current federal funds rate?",
        expected(
            final=["current", "federal funds"],
            inputs=[inp("federal funds", True, "none")],
            current=True,
            include_actions=["web_search"],
            include_caps=["retrieve_current_information"],
        ),
    ),
    case(
        "fresh_fact_check_council_001",
        "fact_checking",
        "Fact-check whether Seattle city council passed a new tenant ordinance this month.",
        expected(
            final=["Fact-check", "tenant ordinance"],
            inputs=[inp("Seattle city council", True, "none")],
            current=True,
            include_actions=["web_search", "fact_checking"],
            include_caps=["verify_current_information"],
            precede=[{"before": "verify", "after": "answer"}],
        ),
    ),
    case(
        "fresh_snowflake_query_001",
        "generic_coding_parameters",
        "Write a Snowflake SQL query for daily active users from events(user_id, event_date).",
        expected(
            final=["SQL query", "daily active"],
            inputs=[inp("events user_id event_date", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "fresh_graphql_query_001",
        "generic_coding_parameters",
        "Write a GraphQL query that fetches repository name, owner, and star count.",
        expected(
            final=["GraphQL query", "repository"],
            inputs=[inp("GraphQL query", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "fresh_typescript_function_001",
        "generic_coding_parameters",
        "Write a TypeScript function groupByStatus(items) that returns a map from status to items.",
        expected(
            final=["TypeScript function", "groupByStatus"],
            inputs=[inp("groupByStatus", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "fresh_regex_pattern_001",
        "generic_coding_parameters",
        "Write a regex pattern that matches invoice IDs like INV-2026-0042.",
        expected(
            final=["regex", "invoice"],
            inputs=[inp("invoice IDs", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["generate_code"],
        ),
    ),
    case(
        "fresh_repo_references_001",
        "file_reading",
        "Locate references to legacyBilling in the codebase and summarize affected modules.",
        expected(
            final=["references", "legacyBilling"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
            precede=[{"before": "search", "after": "summarize"}],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_repo_deprecated_flags_001",
        "file_reading",
        "Scan the repo for deprecated feature flags.",
        expected(
            final=["Scan", "deprecated"],
            inputs=[inp("repository files", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["search_provided_files"],
        ),
        [{"name": "repository files", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_local_file_read_001",
        "file_path_reading",
        "Read settings/prod.json and summarize enabled integrations.",
        expected(
            final=["Read", "integrations"],
            inputs=[inp("settings/prod.json", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_file"],
            precede=[{"before": "extract", "after": "summarize"}],
        ),
        [{"name": "settings/prod.json", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_code_edit_001",
        "code_file_read_write",
        "Update src/payments/refunds.py to handle zero-dollar refunds and add tests.",
        expected(
            final=["Update", "refunds"],
            inputs=[inp("src/payments/refunds.py", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["file_reading", "file_writing"],
            include_caps=["inspect_existing_code", "modify_code"],
            precede=[{"before": "inspect", "after": "modify"}],
        ),
        [{"name": "src/payments/refunds.py", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_run_tests_fix_001",
        "code_execution",
        "Run tests, fix failing imports in service/app.py, and report the change.",
        expected(
            final=["Run tests", "imports"],
            inputs=[inp("service/app.py", True, "file_path")],
            include_formats=["file_path"],
            current=False,
            include_actions=["code_execution", "file_reading", "file_writing"],
            include_caps=["execute_code", "inspect_existing_code", "modify_code"],
        ),
        [{"name": "service/app.py", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_image_alt_001",
        "image_understanding",
        "Write alt text for the attached checkout screenshot.",
        expected(
            final=["alt text", "checkout"],
            inputs=[inp("checkout", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding"],
            include_caps=["interpret_image_content"],
        ),
        [{"name": "checkout.png", "format": "image", "available": True}],
    ),
    case(
        "fresh_image_receipt_001",
        "image_understanding",
        "Read the attached receipt image and extract the total.",
        expected(
            final=["extract", "total"],
            inputs=[inp("receipt", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding"],
            include_caps=["extract_information_from_image"],
        ),
        [{"name": "receipt.png", "format": "image", "available": True}],
    ),
    case(
        "fresh_image_measure_001",
        "unsupported_missing_scale",
        "Measure the real-world width of the whiteboard in the attached image.",
        expected(
            final=["Measure", "whiteboard"],
            inputs=[inp("image", True, "image"), inp("scale", False, "unknown")],
            missing=["scale"],
            include_formats=["image"],
            current=False,
            include_actions=["image_understanding", "user_input"],
            include_caps=["request_missing_input"],
            precede=[{"before": "request_missing_input", "after": "measure"}],
        ),
        [{"name": "whiteboard.jpg", "format": "image", "available": True}],
    ),
    case(
        "fresh_image_banner_001",
        "image_generation",
        "Create a banner graphic for a hiring webinar with teal and black colors.",
        expected(
            final=["banner", "webinar"],
            inputs=[inp("hiring webinar", True, "none")],
            current=False,
            include_actions=["image_generation"],
            include_caps=["generate_image"],
        ),
    ),
    case(
        "fresh_image_remove_bg_001",
        "image_editing",
        "Remove the background from the attached product cutout.",
        expected(
            final=["Remove", "background"],
            inputs=[inp("product cutout", True, "image")],
            include_formats=["image"],
            current=False,
            include_actions=["image_generation"],
            include_caps=["transform_image"],
        ),
        [{"name": "cutout.png", "format": "image", "available": True}],
    ),
    case(
        "fresh_pdf_summary_001",
        "attached_pdf",
        "Summarize the attached audit report and list open risks.",
        expected(
            final=["Summarize", "audit report"],
            inputs=[inp("audit_report.pdf", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading"],
            include_caps=["extract_information_from_attached_document"],
            alt_caps=["summarize_document"],
            precede=[{"before": "extract", "after": "summarize"}],
        ),
        [{"name": "audit_report.pdf", "format": "pdf", "available": True}],
    ),
    case(
        "fresh_pdf_invoice_calc_001",
        "pdf_calculation",
        "From the attached invoice PDF, calculate total late fees.",
        expected(
            final=["calculate", "late fees"],
            inputs=[inp("invoice", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["extract_information_from_attached_document"],
            alt_caps=["compute_numeric_result"],
            precede=[{"before": "extract", "after": "compute"}],
        ),
        [{"name": "invoice.pdf", "format": "pdf", "available": True}],
    ),
    case(
        "fresh_workbook_growth_001",
        "attached_spreadsheet",
        "Calculate month-over-month growth from the attached workbook.",
        expected(
            final=["Calculate", "growth"],
            inputs=[inp("workbook", True, "attached_file")],
            include_formats=["attached_file"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["analyze_provided_dataset"],
            precede=[{"before": "extract", "after": "calculate"}],
        ),
        [{"name": "growth.xlsx", "format": "attached_file", "available": True}],
    ),
    case(
        "fresh_attached_csv_aggregate_001",
        "attached_structured_data",
        "Aggregate refunds by reason from the attached CSV.",
        expected(
            final=["Aggregate", "refunds"],
            inputs=[inp("CSV", True, "structured_data")],
            include_formats=["structured_data"],
            current=False,
            include_actions=["file_reading", "calculation"],
            include_caps=["analyze_provided_dataset"],
        ),
        [{"name": "refunds.csv", "format": "structured_data", "available": True}],
    ),
    case(
        "fresh_write_file_update_001",
        "file_writing",
        "Create notes/rollout.md from this update: support trained, launch approved, comms scheduled.",
        expected(
            final=["Create", "rollout"],
            inputs=[inp("notes/rollout.md", True, "file_path"), inp("update", True, "pasted_text")],
            include_formats=["file_path", "pasted_text"],
            current=False,
            include_actions=["file_writing"],
            include_caps=["write_file"],
        ),
        [{"name": "notes/rollout.md", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_merge_pdfs_001",
        "file_merge",
        "Merge the attached contract PDFs into one packet.",
        expected(
            final=["Merge", "PDFs"],
            inputs=[inp("contract_a.pdf", True, "pdf")],
            include_formats=["pdf"],
            current=False,
            include_actions=["file_reading", "file_writing"],
            include_caps=["combine_files"],
        ),
        [
            {"name": "contract_a.pdf", "format": "pdf", "available": True},
            {"name": "contract_b.pdf", "format": "pdf", "available": True},
        ],
    ),
    case(
        "fresh_status_email_001",
        "text_generation",
        "Draft a short status email saying onboarding is complete and support coverage starts Monday.",
        expected(
            final=["status email", "onboarding"],
            inputs=[inp("onboarding", True, "none")],
            current=False,
            include_actions=["none"],
            include_caps=["draft_text"],
        ),
    ),
    case(
        "fresh_json_file_write_001",
        "file_writing",
        "Create data/summary.json from this summary: alpha is done, beta is blocked, gamma starts next week.",
        expected(
            final=["Create", "summary"],
            inputs=[inp("data/summary.json", True, "file_path"), inp("summary", True, "pasted_text")],
            include_formats=["file_path", "pasted_text"],
            current=False,
            include_actions=["file_writing"],
            include_caps=["write_file"],
        ),
        [{"name": "data/summary.json", "format": "file_path", "available": True}],
    ),
    case(
        "fresh_arithmetic_001",
        "calculation",
        "What is 48 / 6 + 7 * 3?",
        expected(
            final=["48", "7"],
            inputs=[inp("numeric", True, "none")],
            current=False,
            include_actions=["calculation"],
            include_caps=["compute_numeric_result"],
        ),
    ),
]


def main() -> None:
    if len(CASES) != 50:
        raise SystemExit(f"expected 50 fresh holdout cases, found {len(CASES)}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        for index, row in enumerate(CASES):
            row = {"row_index": index, **row}
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    print(f"wrote {len(CASES)} cases to {OUT}")


if __name__ == "__main__":
    main()
